# Force Java 21 from Android Studio
org.gradle.java.home=C:/Program Files/Android/Android Studio/jbr
# Override Java version requirement
org.gradle.java.installations.fromPaths=C:/Program Files/Android/Android Studio/jbr
